import type { Metadata } from "next";
import {GeistSans} from "geist/font/sans";
import {GeistMono} from "geist/font/mono";
// import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = GeistSans;
const geistMono = GeistMono;

// const geistSans = GeistSans({
//   variable: "--font-geist-sans",
//   // subsets: ["latin"],
// });

// const geistMono = GeistMono({
//   variable: "--font-geist-mono",
//   // subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="relative w-full flex justify-center items-center">
        <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
